name: Run WDIO Tests and Upload Allure Report for Android Native Demo App

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
        BROWSERSTACK_USERNAME: ${{secrets.BROWSERSTACK_USERNAME}}
        BROWSERSTACK_ACCESS_KEY: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
        BROWSERSTACK_APP_ID: ${{secrets.BROWSERSTACK_APP_ID}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:pixel3
        continue-on-error: true

      - name: Generate Allure Report
        if: always()
        run: npm run report:generate

      - name: Deploy Report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: reports/allure-report